[project]
name = "veda-data-airflow"
version = "0.1.0"
description = "Function and deployment code for producing cloud-optimized data products and STAC metadata for interfaces such as https://github.com/NASA-IMPACT/veda-ui."
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "apache-airflow==3.0.2",
    "apache-airflow-providers-standard",
    "pytest>=8.3.5",
]

[dependency-groups]
dev = [
    "pre-commit==4.6.2"
]
deploy = [
    "boto3==1.37.0",
    "requests==2.31.0"
]
test = [
    "coverage",
    "moto>=4.2.13",
    "boto3>=1.37.0",
    "smart-open>=7.1.0",
    "requests-mock",
    "xarray",
    "xstac",
    "stac_pydantic",
    "mypy_boto3_s3",
    "rasterio",
    "rio_stac",
    "virtualenv",
]
airflow-worker = [
    "apache-airflow-providers-amazon==9.8.0",
    "botocore",
    "cryptography",
    "pycurl",
    "psycopg2-binary",
    "apache-airflow-providers-celery",
    "affine",
    "netCDF4",
    "requests",
    "rio-cogeo",
    "smart-open",
    "apache-airflow-providers-postgres",
    "apache-airflow-providers-common-sql",
    "apache-airflow-providers-http",
    "typing-extensions",
    "pyOpenSSL",
    "stac-pydantic",
    "fsspec",
    "s3fs",
    "xarray",
    "xstac",
    "pystac",
    "rasterio",
    "rio_stac",
    "GeoAlchemy2",
    "geopandas==0.14.4",
    "fiona==1.9.6",
    "h5netcdf",
    "rioxarray",
    "apache-airflow-providers-slack",
    "apache-airflow-providers-slack[http]",
    "stactools",
    "stactools-noaa-hrrr"
]
airflow-service = [
    "apache-airflow-providers-amazon==9.8.0",
    "botocore",
    "cryptography",
    "pycurl",
    "psycopg2-binary",
    "apache-airflow-providers-celery",
    "apache-airflow-providers-postgres",
    "apache-airflow-providers-slack",
    "apache-airflow-providers-slack[http]",
    "apache-airflow[github_enterprise]",
    "affine",
    "netCDF4",
    "requests",
    "rio-cogeo",
    "smart-open",
    "apache-airflow-providers-common-sql",
    "typing-extensions",
    "pyOpenSSL",
    "stac-pydantic",
    "fsspec",
    "s3fs",
    "xarray",
    "xstac",
]

[tool.uv]
default-groups = ["dev", "deploy", "test"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "AIR",  # apache-airflow
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes
    "I",    # isort
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
    "PTH",  # flake8-use-pathlib
    "RET",  # flake8-return
    "TID",  # flake8-tidy-imports
    "TC",   # flake8-type-checking
    "ISC",  # flake8-implicit-str-concat
    "ICN",  # flake8-import-conventions
]
ignore = [
  "BLE001",  # Blind Exceptions
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.markdownlint-cli2.config]
MD013 = false
MD033 = { allowed_elements = ["span"] }
