name: Deploy

inputs:
  env_aws_secret_name:
    required: true
    type: string
  env-file:
    required: true
    type: string
  dir:
    required: false
    type: string
    default: "."
  script_path:
    required: true
    type: string
  backend_stack_name:
    required: true
    type: string
  auth_stack_name:
    required: true
    type: string
  project_prefix:
    required: true
    type: string
  stage:
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Install python dependencies
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: pip install -r deploy_requirements.txt

    - name: Get relevant environment configuration from aws secrets
      shell: bash
      working-directory: ${{ inputs.dir }}
      env:
        SECRET_SSM_NAME: ${{ inputs.env_aws_secret_name }}
        AWS_DEFAULT_REGION: us-west-2
      run: |
        python ${{ inputs.script_path }} --secret-id ${{ inputs.env_aws_secret_name }} --stack-name ${{ inputs.auth_stack_name}},${{ inputs.backend_stack_name}}
        echo "PROJECT_PREFIX=${{ inputs.project_prefix }}" >> .env
        echo "STAGE=${{ inputs.stage }}" >> .env
        echo "PREFIX=${{ inputs.project_prefix }}-${{ inputs.stage }}" >> .env

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.3

    - name: Deploy
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        ./scripts/deploy.sh ${{ inputs.env-file }} <<< init
        ./scripts/deploy.sh ${{ inputs.env-file }} <<< plan
